#!/bin/bash
if [ $EUID -eq 0 ];then
	echo "It's not recomended to run XDM  as root, as it can cause problems"
fi
/opt/xdman/jre/bin/java -Dsun.java2d.xrender=false -Xmx1024m -jar /opt/xdman/xdman.jar
